improved zsh config to load pyenv correctly

diff --git a/terminal/zshenv b/terminal/zshenv
--- a/terminal/zshenv
+++ b/terminal/zshenv
@@ -1,4 +1,4 @@
-#!/usr/bin/env sh
+#!/usr/bin/env zsh
 #
 #   Configuration inside `~/.zshenv` is source by both interactive and
 #   not interactive shells (typically, GUI programs), and hence, MacVim
@@ -39,25 +39,26 @@ fi
 
 setenv ZSH "$HOME/.oh-my-zsh" # required by OhMyZSH!
 
+# => load local configuration, if available
+path_prepend $DOTCASTLE/bin
+# ssh-add $HOME/.ssh/`whoami` &>/dev/null || echo "SSH identity could not be added!"
+[[ -s ~/.zshenv.local ]] && source ~/.zshenv.local
+export GPG_TTY=$(tty)
+
 # => ensure that homebrew is in our path.
 path_prepend "${BREW_PREFIX}/bin"
 path_prepend "${BREW_PREFIX}/sbin"
 
 # load rbenv and pyenv, if available
-setenv RBENV_ROOT $BREW_PREFIX/var/rbenv
-is_installed rbenv && init_cache rbenv "rbenv init --no-rehash - zsh"
-setenv PYENV_ROOT $BREW_PREFIX/var/pyenv
 export WORKON_HOME=~/.venv
 export PROJECT_HOME=~/Code/python/workspace
-is_installed pyenv && init_cache pyenv "pyenv init --no-rehash - zsh"
-# is_installed pyenv-virtualenv-init && init_cache pyenv-virtualenv-init "pyenv virtualenv-init -"
-
-# Python environment
-# pip should only run if there is a virtualenv currently activated
 export PIP_REQUIRE_VIRTUALENV=true
-# cache pip-installed packages to avoid re-downloading
 export PIP_DOWNLOAD_CACHE=$HOME/.pip/cache
-# allow access to install python packages globally via gpip
+setenv RBENV_ROOT $BREW_PREFIX/var/rbenv
+setenv PYENV_ROOT $BREW_PREFIX/var/pyenv
+is_installed rbenv && init_cache rbenv "rbenv init --no-rehash - zsh"
+is_installed pyenv && init_cache pyenv "pyenv init -"
+is_installed pyenv-virtualenv && init_cache pyenv-virtualenv "pyenv virtualenv-init -"
 gpip(){ PIP_REQUIRE_VIRTUALENV="" pip "$@"; }
 gpip3(){ PIP_REQUIRE_VIRTUALENV="" pip3 "$@"; }
 
@@ -66,9 +67,3 @@ setenv GOPATH $HOME/.golang
 path_append "${GOPATH}/bin"
 path_append "${BREW_PREFIX}/opt/go/libexec/bin"
 path_append ~/.composer/vendor/bin
-
-# => load local configuration, if available
-path_prepend $DOTCASTLE/bin
-# ssh-add $HOME/.ssh/`whoami` &>/dev/null || echo "SSH identity could not be added!"
-[[ -s ~/.zshenv.local ]] && source ~/.zshenv.local
-export GPG_TTY=$(tty)
